logging:
  root_log_level: INFO
  # When running in k8s, use JSON logger via env setting
  # formatter: json
  formatter: "json"
  child_log_levels:
    mchpy: DEBUG
    mchpy.audit.http_audit: INFO
main:
  app_name: Flexpart-IFS
  openmp_config:
    num_threads: 16
    stack_size: 100M
  input:
    step_unit: hours
  aws:
    s3:
      nwp_model_data:
        region: eu-central-2
        name: flexpart-input
        retries: 10
      output:
        region: eu-central-2
        name: flexpart-output
        retries: 10
