default:
  - build:
      - checkGivenSemanticVersion:
          checkSemanticVersion:
      - getSemanticVersion:
          gitCalculateSemanticVersion:
      - getImageName:
          containerConstructImageName:
      - getImageNamePublic:
          - containerConstructImageName:
              containerRegistries:
                - docker-public-nexus.meteoswiss.ch
              primaryRegistry:
                docker-public-nexus.meteoswiss.ch
      - getImageNameCSCS:
          - containerConstructImageName:
              containerRegistries:
                - container-registry.meteoswiss.ch
              primaryRegistry:
                container-registry.meteoswiss.ch
      - artifacts:
          - containerBuildImage:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              target: tester
              extraArgs:
                - --build-arg
                - VERSION=${var.semanticVersion}
                - --secret=id=spack_buildcache_user,env=NXUSER
                - --secret=id=spack_buildcache_password,env=NXPASS
                - --runtime=${var.crunPath}
          - containerBuildImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}
              target: runner
              extraArgs:
                - --build-arg
                - VERSION=${var.semanticVersion}
                - --secret=id=spack_buildcache_user,env=NXUSER
                - --secret=id=spack_buildcache_password,env=NXPASS
                - --runtime=${var.crunPath}
              pullAlways: false
  - test:
      # TODO DT-276 create local testing task
      # TODO DT-276 set test_data paths in Jenkinsfile?
      # TODO DT-276 replace test_ci.sh with mchbuild tasks?
      # TODO DT-276 make container CLI in mchbuild configurable (i.e. support sarus)
      - unit:
          - script: |
              mkdir -p test_reports
              sarus pull ${var.containerImageName}-tester:${var.semanticVersion}
              sarus run \
                    -e TEST_DATA=/scratch/test_data \
                    --mount=type=bind,source=$PWD/test_reports,destination=/scratch/test_reports \
                    --mount=type=bind,source=/oprusers/trajond/flexpart-ifs/test_data,destination=/scratch/test_data \
                    ${var.containerImageName}-tester:${var.semanticVersion}
      - lint:
          - script: mkdir -p test_reports
          - pythonContainerLint:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
              removeLocalImage: false
          - pythonContainerTypeCheck:
              imageName: ${var.containerImageName}-tester
              imageTag: ${var.semanticVersion}
              packageManager: ''
              pullAlways: false
              removeLocalImage: false
  - publish:
      - testArtifacts:
          - containerPublishImage:
              imageToTag: ${var.containerImageName}-tester:${var.semanticVersion}
              imageName: ${var.publicContainerImageName}-tester
              imageTag: ${var.semanticVersion}
              removeLocalImage: false
              removeImageToTag: false
      - artifacts:
          - containerPublishImage:
              imageName: ${var.containerImageName}-aws
              imageTag: ${var.semanticVersion}
              removeLocalImage: false

  - deploy:
      - pypi:
          pythonPublishPackage:
            setPackageVersion: False
            pythonImageName: '3.10'
            pullAlways: false

  # TODO DT-276 use cleanup task from mchbuild 0.12
  - clean:
      - images:
          script: |
            if test -n "${var.semanticVersion}"; then
              podman image rm -f $(podman image ls -q \
                -f "label=ch.meteoswiss.project=${var.project}-${var.semanticVersion}") || :
            fi

variables:
  project: flexpart-ifs
  # default full image name, useful when running tasks locally
  image: ${var.containerImageName}:${var.semanticVersion}
  solution: dispersionmodelling
  notifyOnNightlyFailure: p_dispersionmodelling@meteoswiss.ch
  # TODO DT-276 extract common values
  publicContainerImageName: docker-public-nexus.meteoswiss.ch/dispersionmodelling/flexpart-ifs
  containerImageName: docker-intern-nexus.meteoswiss.ch/dispersionmodelling/flexpart-ifs
  semanticVersion: 0.0.0  # is overwritten in Jenkins
  containerRegistries: [
    'docker-intern-nexus.meteoswiss.ch',
    'docker-public-nexus.meteoswiss.ch'
  ]
  crunPath: /usr/bin/crun
