#!/bin/bash
#+==============================================================================
# Use pyflexplot to produce the standard plot set for the NAZ.
#
# Author:      Pirmin Kaufmann
#-==============================================================================

# Settings (should be equal to settings in test-fp)
# --------
# File for automatic job numbering
job_no_file=$HOME/.flexpart_job
# Root directory for job directories (see also test-fp script)
job_root=$SCRATCH/flexpart/job
# File with some metadata missing in nc file (see also test-fp script)
plot_info_file=plot_info
# Maximum number of plot files to list
list_max=8
# --------

# Defaults
# --------
# Number of parallel threads used in pyflexplot
ncpus=5
# --------

# Functions
# ---------
function display_help {
    # Show script usage
    cat >&2 << EOF

Use pyflexplot to produce the standard plot set for the NAZ.
       
Usage: $tag [OPTION]... JOBDIR

  JOBDIR                 Directory in which job was run. FLEXPART output file
                         is searched in $job_root/JOBDIR/output
                         instead of current directory.

Mandatory arguments to long options are mandatory for short options too.
  -c, --clean            delete existing plots before invoking pyflexplot
  -d, --debug            print out additional debug output
  -e, --ensemble         create ensemble plots
  -f, --force            invoke pyflexplot even if plots already exist
  -h, --help             display this help and exit
  -n, --dry-run          print commands without executing them
  -W, --dry-wet          additonally plot dry and wet deposition separately
  -N, --ncpus=NCPUS      use NCPUS parallel threads for pyflexplot
  -O, --operational      use operational pyflexplot from osm
  -p, --preset=PRESET    use pyflexplot with preset PRESET
  -s, --steps            plot step values rather than accumulated values
  -w, --wait             wait for batch job completion, allows to list results

EOF
} # function display_help

function cleanup_plot_dir {
    # Check if plots exist
    if ls $1/*p[dn][fg] > /dev/null 2>&1 ; then
        echo -n $tag: "Plot files already exist in $1"
        if [[ -n $clean ]] ; then
            echo ", deleting."
            rm -rf $1/*{png,pdf}
        elif [[ -z $force ]] ; then
            echo ", use --force to overwrite."
            exe_cmd="echo -e $tag: SKIP: Plots already present, skipping:\n\e[07;32m \e[0m  "
            wait_opt=skipped
        else
            echo ", overwriting."
        fi
    fi
} # function cleanup_plot_dir

# Initialization
# --------------
tag=$(basename $0)

# Parse arguments
# ---------------
iarg=0
while (( $# > 0 )) ; do
    case "$1" in
        -c | --clean)
            clean=yes
            ;;
        -d | --debug)
            debug=yes
            ;;
        -n | --dry-run)
            dry_run=yes
            ;;
        -D | --dry-wet)
            dry_wet=yes
            ;;
        -e | --ensemble)
            ensemble=yes
            ;;
        -f | --force)
            force=yes
            ;;
        -h | --help)
            display_help
            exit
            ;;
        -N | --ncpus*)
            # Mandatory option argument with or without =
            if [[ "$1" == *=* ]] ; then
                ncpus="${1#*=}"
            else
                (( $# > 1 )) && shift && ncpus="$1"
            fi
            ;;
        -O | --operational)
            operational=yes
            ;;
        -p | --preset*)
            # Mandatory option argument with or without =
            if [[ "$1" == *=* ]] ; then
                preset="${1#*=}"
            else
                (( $# > 1 )) && shift && preset="$1"
            fi
            ;;
        -s | --steps)
            steps=yes
            ;;
        -w | --wait)
            wait_opt=-w
            ;;
        -*)
            echo $tag: "Unknown option: $1"
            exit 1
            ;;
        *)
            (( iarg++ ))
            case $iarg in
                1)
                    jobdir="$1"
                    ;;
                *)  # Additional arguments
                    echo $tag: "Too many arguments: $1"
                    exit 1
                    ;;
            esac
            ;;
    esac
    shift
done

# Check argument: Job directory
if [[ -z $jobdir ]] ; then
    if [[ -f $job_no_file ]] ; then
        jobdir=$(cat $job_no_file)
        echo $tag: "Missing argument: Job name/number, assuming last: $jobdir"
    else
        echo $tag: "Missing argument: Job name/number"
        exit 1
    fi
fi

# Start Processing
# ----------------

# Option -n, --dry-run
if [[ -n $dry_run ]] ; then
    # Enable escape sequences in echo with option -e
    exe_cmd="echo -e \e[07;32m \e[0m  "
    echo $tag: "INFO: Option --dry-run set," \
        "printing commands without executing them."
    echo -n $tag: "Skipped commands are marked with: "
    $exe_cmd
fi

# Change to job directory
if [[ -n $jobdir ]] ; then
    jobout=$job_root/$jobdir/output
    plotdir=$job_root/$jobdir/plot
    pushd $job_root/$jobdir > /dev/null
else
    jobout=.
    plotdir=.
fi
infiles=( $jobout/*.nc )
echo $tag: "Producing plots from: ${infiles[*]}"
echo $tag: "Producing plots in: $plotdir"

# Derive variables 'job' (job name or number) and 'resol' (resolution)
# from test-fp.log
if [[ ! -e test-fp.log ]] ; then
    echo $tag: "ERROR: Cannot derive resolution due to missing logfile: $pwd/test-fp.log"
    exit 1
fi
eval $(tail -n 1 test-fp.log | sed 's/.*\(resol=[a-z0-9]*\) .*/\1/')
echo $tag: "Resolution as determined from $PWD/test-fp.log: $resol"

# Supersede job name from logfile if name specified explicitly
[[ -n $jobdir ]] && job="$jobdir"

# Define preset, use pyflexplot --preset=? to obtain the list of presets
if [[ -z $preset ]] ; then
    case "$resol" in
        i1) preset=opr/icon-ch1-ctrl/all_* ;;
        i2)
            if [[ -n $ensemble ]] ; then
                preset=opr/icon-ch2-eps/all_*
            else
                preset=opr/icon-ch1-ctrl/all_*
            fi
        ;;
        1e) preset=opr/cosmo-1e-ctrl/all_* ;;
        2e)
            if [[ -n $ensemble ]] ; then
                preset=opr/cosmo-2e/all_*
            else
                preset=opr/cosmo-1e-ctrl/all_*
            fi
        ;;
        f)  preset=opr/ifs-hres-eu/all_*   ;;
        g)  preset=opr/ifs-hres/all_*      ;;
        *)  echo $tag: "Unknown resolution: $resol"
            exit 1 ;;
    esac
fi
echo $tag: "Preset used: $preset"

# Derive basetime from file plot_info
# Load plot_info if present
if [[ -f output/$plot_info_file ]] ; then
    basetime=$(cat output/$plot_info_file)
    echo $tag: "Retrieved base time from output/$plot_info_file: $basetime"
    base_time_opt="--setup base_time ${basetime}"
else
    echo $tag: "Plot information file not found: output/$plot_info_file"
fi

# Determine executable
if [[ -z $operational ]] ; then
    pyflexplot=$(which pyflexplot)
    if [[ ! -e $pyflexplot ]] ; then
        echo $tag: "No pyflexplot executable found in PATH, exiting."
        exit 1
    fi
else
    # Run operational pyflexplot from $OPR_BIN
    # Load definition of OPR_BIN
    [[ -z $OPR_SETUP_DIR ]] && source /oprusers/osm/.opr_setup_dir
    pyflexplot=$OPR_BIN/pyflexplot
    if [[ ! -x $pyflexplot ]] ; then
        echo $tag: "ERROR: No operational pyflexplot found: $pyflexplot"
        exit 1
    fi
    echo $tag: "INFO: Using operational environment: $pyflexplot"
fi

# Report executable
echo $tag: "Using pyflexplot executable:" \
    $(ls -l --time-style=long-iso $pyflexplot | cut -d\  -f6- )

# Steps option
if [[ -n $steps ]] ; then
    plotdir=${plotdir}_steps
    echo $tag: "Steps option--steps set, new plot directory: $plotdir"
    integrate_opt="--setup integrate false"
fi

# Not implemented: automatic submission for ensemble plots
if [[ -n $ensemble ]] ; then
    echo $tag: "Link ensemble output into $jobdir/output," \
    "replace ensemble number in infile by {ens_member:03}," \
    "add quotes around infile and a backslash before the \$," \
    "and submit job manually"
    infiles=${infiles[0]}
    exe_cmd=echo
fi

# Submit job
for infile in ${infiles[*]} ; do
    [[ -z $ensemble ]] && echo $tag: "Submitting job to plot: ${infile}"
    cleanup_plot_dir $plot_dir
    # Option -w: wait for job to complete
    [[ -n $wait_opt ]] && echo $tag: "Waiting for job completion."
    $exe_cmd batchPP -t 1 -T 5 -n pfp_$jobdir $wait_opt -- \
        $pyflexplot --preset=$preset --merge-pdfs $integrate_opt \
        --setup infile $infile $base_time_opt \
        --dest=$plotdir \
        --num-procs=\$SLURM_CPUS_PER_TASK
    # Separate deposition option
    if [[ -n $dry_wet ]] ; then
        for depotype in dry wet ; do
            echo $tag: "Dry/wet deposition option --dry-wet set," \
                "additional plot directory: ${plotdir}_${depotype}"
            cleanup_plot_dir ${plotdir}_${depotype}

            $exe_cmd batchPP -t 2 -T 5 -n pfp_$jobdir${depotype} $wait_opt -- \
                $pyflexplot --preset=$preset --merge-pdfs $integrate_opt \
                --setup infile $infile $base_time_opt \
                --setup plot_variable ${depotype}_deposition \
                --dest=${plotdir}_${depotype} \
                --num-procs=\$SLURM_CPUS_PER_TASK
        done
    fi
    [[ -n $ensemble ]] && exit 0 # exit to let user submit job manually
done

if [[ -n $jobdir ]] ; then
    popd > /dev/null
fi

# Check if end of job has been waited for
if [[ -n $wait_opt ]] ; then
    # Count results
    # Use echo with wc -w instead of ls with wc -l to avoid error messages
    n_png=$(echo $plotdir/*png | wc -w)
    n_pdf=$(echo $plotdir/*pdf | wc -w)

    # Report results
    if [[ $wait_opt = skipped ]] ; then
        echo $tag: "Plots already present:"
    else
        echo $tag: "Plots produced:"
    fi
    if (( $n_png > 1 )) ; then
        echo $tag: "Listing png-plots produced in: $plotdir"
        ls $plotdir/*png | head -n $list_max
        (( $n_pdf > $list_max )) && echo "... (total $n_png)"
    fi

    if (( $n_pdf > 1 )) ; then
        echo $tag: "Listing pdf-plots produced in: $plotdir"
        ls $plotdir/*pdf | head -n $list_max
        (( $n_pdf > $list_max )) && echo "... (total $n_pdf)"
    fi
else
    # Job running, only report output dir
    echo $tag: "Not waiting for job completion (see option --wait)."
    echo $tag: "Plots will be produced in: $plotdir"
fi

# End of script
exit
